# -*- coding: utf-8 -*-
"""Scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s2gDsSMbX70ULJecHrrM4h89DnHeGzk3
"""

pip install google-play-scraper

import pandas as pd
from google_play_scraper import Sort, reviews

# App ID e-wallet Indonesia from Play Store
apps = {
    'GoPay': 'com.gojek.app',
    'OVO': 'ovo.id',
    'DANA': 'id.dana'
}

all_reviews = []

# Extract user reviews for each application
for app_name, app_id in apps.items():
    print(f"Scraping review data for: {app_name}...")

    # Retrieve the 5000 most recent reviews per application
    result, _ = reviews(
        app_id,
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=5000
    )

    # Append the application identifier to each review entry
    for item in result:
        item['app_name'] = app_name
        all_reviews.append(item)

# Convert the extracted raw data into a Pandas DataFrame
df = pd.DataFrame(all_reviews)

df

# Filter and retain only the relevant attributes
cols_to_keep = ['app_name', 'userName', 'score', 'at', 'content', 'appVersion']
df_clean = df[cols_to_keep]

# Display data summary and preview
print("\nExtraction completed successfully! Preview of the dataset:")
display(df_clean.head())
print(f"\nTotal collected reviews: {len(df_clean)} rows")

# Export & Download CSV
df_clean.to_csv('ewallet_reviews.csv', index=False)

from google.colab import files
files.download('ewallet_reviews.csv')